#!/bin/zsh

LBLUE="\033[1;34m"
LRED="\033[1;31m"
YELLOW="\033[1;33m"
NC="\033[0m"

if [[ $1 == "status" ]]; then
  gitCommand="status"
  type="status"
elif [[ $1 == "log" ]]; then
  gitCommand="--no-pager log --date=local --decorate=short"
  type="log"
  if [[ $2 == "--before"* ]] || [[ $2 == "--after"* ]]; then
    # todo extract to func

    IFS=\= read -r left1 right1 <<<"$2"
    if [[ $right1 =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}$ ]]; then
      dateRange1="$2"
    else
      echo "Date $right1 is in an invalid format (not YYYY-MM-DD)"
      exit
    fi

    IFS=\= read -r left2 right2 <<<"$3"
    if [[ $3 == "--before"* ]] || [[ $3 == "--after"* ]]; then
      if [[ $left1 != "$left2" ]] && [[ $right2 =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}$ ]]; then
        dateRange2="$3"
      else
        echo "Date $right2 is in an invalid format (not YYYY-MM-DD)"
        exit
      fi
    fi
    gitCommand="$gitCommand $dateRange1 $dateRange2"
  fi
  if [[ $3 == "onlyself" ]] || [[ $4 == "onlyself" ]]; then
    filterByAuthor=true
  fi
  echo "$gitCommand"
else
  echo "You must specify a command"
  exit
fi

gitAuthor="$(eval "git config --global --get user.name")"
gitEmail="$(eval "git config --global --get user.email")"

printf "$YELLOW> Checking repositories with command '$type' ...\n"

root=$PWD
repos=0
numReposMatched=0
numCommits=0
find . -type d \( -path "*/node_modules/*" -o -path "*/.idea/*" -o -path "*/.vscode/*" \) -prune -false -o -name '*.git' | while read -r dir; do
  # sanity check
  if [[ $dir == *"/.git" ]]; then
    ((repos++))
    # todo combine replaces
    pure="${dir//\/.git/}"
    pure="${pure//./}"

    # cd into repo
    eval "cd $root/$pure"
    gst="$(eval "git $gitCommand")"
    if [[ $type == "status" ]]; then

      if [[ $gst == *"Your branch is ahead"* ]]; then
        ((numCommits++))
        ((numReposMatched++))
        printf "$LBLUE"
        printf "$pure\n$LRED"
        printf "$gst" | sed -n 1,2p

        printf "\n$NC"
        printf %"$COLUMNS"s | tr " " "-"
      fi
    elif [[ $type == "log" ]] && [[ $gst == *" "* ]]; then
      if [[ $filterByAuthor ]]; then
        hasPrintedRepoName=false
        commitLine=""
        while read -r line; do
          if [[ $line == *"Author"* ]]; then
            if [[ $line == *"Author: $gitAuthor <$gitEmail>"* ]]; then
              ((numCommits++))
              authorMatched=true

              if [[ $hasPrintedRepoName == "false" ]]; then
                printf "$YELLOW"
                printf "$pure\n$LRED"
                hasPrintedRepoName=true
              fi
              echo "$LBLUE$commitLine"
              echo "$LRED$line"
            else
              authorMatched=false
            fi
          elif [[ "$line" == *"commit"* ]]; then
            commitLine="$line"
            authorMatched=false
          elif [[ $authorMatched == "true" ]]; then
            echo "$line"
          fi
        done <<<"$gst"
        ((numReposMatched++))
        printf "\n$NC"
        printf %"$COLUMNS"s | tr " " "-"
      else
        printf "$LBLUE"
        printf "$pure\n$LRED"
        printf "$gst"
        printf "\n$NC"
        printf %"$COLUMNS"s | tr " " "-"
      fi
    fi
  fi
done

if [[ $type == "status" ]]; then
  echo "${YELLOW}> Checked $repos repositories, $numReposMatched are ahead with a total of $numCommits commits"
elif [[ $type == "log" ]]; then
  if [[ $filterByAuthor ]]; then
    echo "${YELLOW}> Checked $repos repositories, $numReposMatched of which contained a total of $numCommits commits by you within the given date range"
  else
    echo "${YELLOW}> Checked $repos repositories, $numReposMatched contained commits within the given date range"
  fi
fi
