#!/bin/zsh

LBLUE="\033[1;34m"
LRED="\033[1;31m"
YELLOW="\033[1;33m"
NC="\033[0m"

args=("$@")

validateDate() {
  IFS=\= read -r left right <<<"$1"
  if [[ $right =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}$ ]]; then
    validDate=$1
    return 0
  else
    echo "Date $right is in an invalid format (not YYYY-MM-DD)"
    return 1
  fi
}

insertSeparator() {
  printf "\n$NC"
  printf %"$COLUMNS"s | tr " " "-"
}

printRepoPath() {
  printf "$LBLUE"
  printf "$pure\n"
}

if [[ ${args[1]} == "status" ]]; then
  gitCommand="status"
  type="status"
elif [[ ${args[1]} == "log" ]]; then
  gitCommand="--no-pager log --date=local --decorate=short"
  type="log"
  for arg in ${args}; do
    if [[ $arg == "--before"* ]] || [[ $arg == "--after"* ]]; then
      if validateDate "$arg"; then
        gitCommand="$gitCommand $validDate"
      else
        exit
      fi
    elif [[ $arg == "onlyself" ]]; then
      filterByAuthor=true
    fi
  done
else
  echo "You must specify a command"
  exit
fi

gitAuthor="$(eval "git config --global --get user.name")"
gitEmail="$(eval "git config --global --get user.email")"

printf "$YELLOW> Checking repositories with command '$gitCommand' ...\n"

root=$PWD
repos=0
numReposMatched=0
numCommits=0
find . -type d \( -path "*/node_modules/*" -o -path "*/.idea/*" -o -path "*/.vscode/*" \) -prune -false -o -name '*.git' | while read -r dir; do
  # sanity check
  if [[ $dir == *"/.git" ]]; then
    ((repos++))
    # todo combine replaces
    pure="${dir//\/.git/}"
    pure="${pure//./}"

    # Run command in repo
    eval "cd $root/$pure"
    gst="$(eval "git $gitCommand")"

    if [[ $type == "status" ]]; then
      if [[ $gst == *"Your branch is ahead"* ]]; then # todo a faster way of matching?
        ((numCommits++))
        ((numReposMatched++))

        printRepoPath
        printf "$LRED$gst" | sed -n 1,2p

        insertSeparator
      fi
    elif [[ $type == "log" ]] && [[ $gst == *" "* ]]; then
      if [[ $filterByAuthor == "true" ]]; then
        hasPrintedRepoPath=false
        commitLine=""
        while read -r line; do
          if [[ $line == *"Author"* ]]; then
            if [[ $line == *"Author: $gitAuthor <$gitEmail>"* ]]; then
              ((numCommits++))
              authorMatched=true
              if [[ $hasPrintedRepoPath == "false" ]]; then
                printRepoPath
                hasPrintedRepoPath=true
                ((numReposMatched++))
              fi
              echo "$YELLOW$commitLine"
              echo "$NC$line"
            else
              authorMatched=false
            fi
          elif [[ $line == *"commit"* ]]; then
            commitLine="$line"
            authorMatched=false
          elif [[ $authorMatched == "true" ]]; then
            echo "$line"
          fi
        done <<<"$gst"

        insertSeparator
      else
        printRepoPath
        ((numReposMatched++))
        while read -r line; do
          if [[ $line == *"commit"* ]]; then
            ((numCommits++))
            echo "$YELLOW$line"
          else
            echo "$NC$line"
          fi
        done <<<"$gst"

        insertSeparator
      fi
    fi
  fi
done

if [[ $type == "status" ]]; then
  echo "${YELLOW}> Checked $repos repositories, $numReposMatched are ahead with a total of $numCommits commits"
elif [[ $type == "log" ]]; then
  if [[ $filterByAuthor == "true" ]]; then
    echo "${YELLOW}> Checked $repos repositories, where $numReposMatched contained $numCommits commits by you within the given date range"
  else
    echo "${YELLOW}> Checked $repos repositories, where $numReposMatched contained $numCommits commits within the given date range"
  fi
fi
